version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "5025:80"   # Aquí ya está el puerto 5025
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  backend:
    build: .
    container_name: sistema_solar_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sistemasolar.rule=PathPrefix(`/api`)"
      - "traefik.http.services.sistemasolar.loadbalancer.server.port=8000"
    networks:
      - web

  adminer:
    image: adminer
    container_name: adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - web

networks:
  web:
    external: false
