name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Versión actualizada

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 191.93.245.227
        username: ndgserver
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Nombre más estándar
        port: 22
        script: |
          # Crear directorio si no existe
          mkdir -p ~/tercerCorteActividad
          cd ~/tercerCorteActividad
          
          # Clonar o actualizar repositorio
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/SamuelDeCordoba/TercerCorteActividad.git .
          fi

          # Limpiar containers previos y desplegar
          docker-compose down || true  # Ignora errores si no hay containers
          docker-compose up -d --build